# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a624b3bd436bd087c4632c5a5b96ed0b690e3af4b8ac38053a9d1952eb229879c5221f253ed4b813a5c49345718f3ec78371bca4b22bd19661e89b7381912fca

test:
  secret_key_base: 977ffdcfb5b434ee15469e3e64c9f27fe64a9721fea6881cb26ec9044701f274d74dca91c10c84cebd48e5d4c358e866146c2eaf1d4aef26e96ec2bd895be931

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
